version: '2.3'
services:
  dockerhost:
    image: qoomon/docker-host
    cap_add:
      - NET_ADMIN
      - NET_RAW
    restart: on-failure
  api:
    build: openeats-api/
    command: /startup/prod-entrypoint.sh
    restart: on-failure
    volumes:
      - static-files:/code/static-files
      - site-media:/code/site-media
    depends_on:
      - dockerhost
    env_file:
      env_stg.list
  web:
    build: openeats-web/
    command: yarn start
    volumes:
      - public-ui:/code/build
    depends_on:
      - api
    env_file:
      env_stg.list
  nginx:
    build: openeats-nginx/
    command: ./start.sh
    ports:
      - "80:80"
    volumes:
      - static-files:/var/www/html/openeats-static/static-files
      - site-media:/var/www/html/openeats-static/site-media
      - public-ui:/var/www/html/openeats-static/public-ui
    depends_on:
      - api
      - web
    env_file:
      env_stg.list
volumes:
  public-ui:
  static-files:
  site-media:

